project:
  type: website
  title: M. Sahar Sajid
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

